In [3]:
# Python program to read image using OpenCV 

# importing OpenCV(cv2) module 
import cv2 

# Save image in set directory 
# Read RGB image 
# img1 = cv2.imread('images/a.png',1)
img0 = cv2.imread('images/a.png',0) 
# img_1 = cv2.imread('images/a.png',-1) 

# imga = 255-img0

# Output img with window name as 'image' 
# cv2.imshow('image1', img1)

cv2.imshow('image0', img0)
# cv2.imshow('image_1', img_1)
# cv2.imshow('image__1', imga) 

# Maintain output window utill 
# user presses a key 
cv2.waitKey(0)

# Destroying present windows on screen 
cv2.destroyAllWindows() 


In [4]:
# importing OpenCV(cv2) module 
import cv2 

img0 = cv2.imread('images/a.png',1)
imga = 255-img0
px = imga[100,100]## It is in order Blue, Green and Red rather than RGB

print(px)
print(imga.shape)
print(imga.size)
blue = imga[:,:,0] ##1 for green and 2 for Red
print(blue)
# cv2.imshow('image0', imga)

# cv2.waitKey(0)
# Destroying present windows on screen 
# cv2.destroyAllWindows() 

[64 70 73]
(241, 422, 3)
305106
[[ 50  49  36 ...  34  39  48]
 [ 80  67  42 ...  32  37  44]
 [ 56  46  37 ...  30  36  48]
 ...
 [ 86  83  80 ...  68  69  82]
 [108 107 104 ...  56  64  77]
 [ 81  80  81 ...  29  48  70]]


In [ ]:
# Log transform the image to inprove the details

# importing OpenCV(cv2) module 
import cv2 
import numpy as np

img0 = cv2.imread('images/a.png',0)
# img1= np.uint8(np.log1p(img0))
img1= np.uint8(np.expm1(img0))
thresh = 1
img2 = cv2.threshold(img1, thresh, 255, cv2.THRESH_BINARY)[1]
cv2.imshow('image0', img0)
cv2.imshow('image01', img1)
cv2.imshow('image02', img2)

cv2.waitKey(0)
# Destroying present windows on screen 
cv2.destroyAllWindows() 

/home/leon/.local/lib/python3.6/site-packages/ipykernel_launcher.py:9: RuntimeWarning: overflow encountered in expm1
  if __name__ == '__main__':


In [ ]:
# We need to increase the sharpness to maximum and reduce the contrast to minimum

In [ ]:
#PIL to increase contrast
from PIL import Image, ImageEnhance 
im = Image.open("images/a.png")
enhancer = ImageEnhance.Contrast(im)
enhanced_im = enhancer.enhance(4.0)
enhanced_im.save("images/enhanced.sample1.png")

In [ ]:
# Increase sharpness using PIL
from PIL import Image, ImageEnhance 
im = Image.open("sample3.png")
enhancer = ImageEnhance.Sharpness(im)
enhanced_im = enhancer.enhance(10.0)
enhanced_im.save("enhanced.sample3.png")


In [ ]:
# Increase the brightness using PIL
from PIL import Image, ImageEnhance 
im = Image.open("sample5.png")
enhancer = ImageEnhance.Brightness(im)
enhanced_im = enhancer.enhance(1.8)
enhanced_im.save("enhanced.sample5.png")

# Using CV
def increase_brightness(img, value=30):
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    h, s, v = cv2.split(hsv)

    lim = 255 - value
    v[v > lim] = 255
    v[v <= lim] += value

    final_hsv = cv2.merge((h, s, v))
    img = cv2.cvtColor(final_hsv, cv2.COLOR_HSV2BGR)
    return img
frame = increase_brightness(frame, value=20)

### Method 3
img = cv2.imread('test.jpg') #load rgb image
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV) #convert it to hsv

h, s, v = cv2.split(hsv)
v += 255
final_hsv = cv2.merge((h, s, v))

img = cv2.cvtColor(final_hsv, cv2.COLOR_HSV2BGR)
cv2.imwrite("image_processed.jpg", img)

In [8]:
#PIL to increase contrast
from PIL import Image, ImageEnhance
import cv2 

img1 = cv2.imread('images/a.png',0) 
cv2.imshow('image1', img1)

im = Image.open("images/a.png")

## enhancer = ImageEnhance.Color(im)
## enhanced_im = enhancer.enhance(0.0)
## enhanced_im.save("images/a11.png")
## img1 = cv2.imread('images/a11.png',0) 
## cv2.imshow('Color', img1)

enhancer = ImageEnhance.Sharpness(im)
enhanced_im = enhancer.enhance(5.0)
enhanced_im.save("images/a12.png")
img2 = cv2.imread('images/a12.png',0) 
cv2.imshow('Sharpness', img2)

img2 = Image.open("images/a12.png")
enhancer = ImageEnhance.Brightness(img2)
enhanced_im = enhancer.enhance(0.5)
enhanced_im.save("images/a14.png")
img4 = cv2.imread('images/a14.png',0) 
cv2.imshow('Brightness', img4)

img3 = Image.open("images/a14.png")
enhancer = ImageEnhance.Contrast(img3)
enhanced_im = enhancer.enhance(0.5)
enhanced_im.save("images/a13.png")
img3 = cv2.imread('images/a13.png',0) 
cv2.imshow('Contrast', img3)

cv2.waitKey(0)

# Destroying present windows on screen 
cv2.destroyAllWindows() 

In [ ]:
# Using CV
import cv2

def increase_brightness(img, value=30):
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    h, s, v = cv2.split(hsv)

    lim = 255 - value
    v[v > lim] = 255
    v[v <= lim] += value

#     v = 12
    final_hsv = cv2.merge((h, s, v))
    img = cv2.cvtColor(final_hsv, cv2.COLOR_HSV2BGR)
    return img

img = cv2.imread('images/a.png') #load rgb image
cv2.imshow('image0', img)
frame = increase_brightness(img, value=10)
cv2.imshow('image1', frame)
cv2.waitKey(0)

# Destroying present windows on screen 
cv2.destroyAllWindows() 

#cv2.imwrite("image_processed.jpg", img)

In [ ]:
from __future__ import print_function
from builtins import input
import cv2 as cv
import numpy as np
import argparse

# Read image given by user
# parser = argparse.ArgumentParser(description='Code for Changing the contrast and brightness of an image! tutorial.')
# parser.add_argument('--input', help='Path to input image.', default='lena.jpg')
# args = parser.parse_args()
# image = cv.imread(cv.samples.findFile(args.input))

image = cv.imread("images/a1.png")
if image is None:
    print('Could not open or find the image: ', args.input)
    exit(0)
new_image = np.zeros(image.shape, image.dtype)
alpha = 1.0 # Simple contrast control
beta = 0    # Simple brightness control
# Initialize values
print(' Basic Linear Transforms ')
print('-------------------------')
try:
    alpha = float(input('* Enter the alpha value [1.0-3.0]: '))
    beta = int(input('* Enter the beta value [0-100]: '))
except ValueError:
    print('Error, not a number')
# Do the operation new_image(i,j) = alpha*image(i,j) + beta
# Instead of these 'for' loops we could have used simply:
# new_image = cv.convertScaleAbs(image, alpha=alpha, beta=beta)
# but we wanted to show you how to access the pixels :)
for y in range(image.shape[0]):
    for x in range(image.shape[1]):
        for c in range(image.shape[2]):
            new_image[y,x,c] = np.clip(alpha*image[y,x,c] + beta, 0, 255)
cv.imshow('Original Image', image)
cv.imshow('New Image', new_image)
# Wait until user press some key
cv.waitKey(0)
cv.destroyAllWindows() 

 Basic Linear Transforms 
-------------------------
* Enter the alpha value [1.0-3.0]: 1
* Enter the beta value [0-100]: 0
